version: "3.3"

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_USER=pdb
      - MYSQL_PASSWORD=pdbpass
      - MYSQL_DATABASE=pdb
      - MYSQL_RANDOM_ROOT_PASSWORD=true

  backend:
    image: catalogapp_backend
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=pdb
      - MYSQL_PASSWORD=pdbpass
    ports:
      - 8000:8080
    depends_on:
      - db
    restart: on-failure
 
  frontend:
    image: coscicorp/catalog_frontend
    ports:
      - 80:3000
    depends_on:
      - backend
    restart: on-failure
